language: r
cache: packages

os:
  - linux
# - osx
# - windows

r: 
  - bioc-devel
# - bioc-release

##notifications:
#  email:
#    on_success: change
#    on_failure: change

bioc_packages: BiocCheck

after_success: R CMD BiocCheck .

#to populate cache in case of timeout
#script: true
