language: r
cache: packages

os:
  - linux
#  - osx

r: 
 - bioc-devel
#- bioc-release

##notifications:
#  email:
#    on_success: change
#    on_failure: change

bioc_packages: BiocCheck

after_success: R CMD BiocCheck .

#populate cache (if timeout; should be false by default)
script: true
