language: r
cache: packages

os:
  - linux
# - osx
# - windows

r: 
  - bioc-devel
# - bioc-release

##notifications:
#  email:
#    on_success: change
#    on_failure: change

r_packages: covr
bioc_packages: BiocCheck

after_success:
  - Rscript -e 'library(covr); codecov(type="all")' 
  - R CMD BiocCheck .

#to populate cache in case of timeout
#script: true
